export const thenExecute = a => b => a.thenExecute(b)
export const thenExecuteAfter = a => b => c => a.thenExecuteAfter(b,c)
export const thenExecuteFor = a => b => c => a.thenExecuteFor(b,c)
export const thenFail = a => b => a.thenFail(b)
export const thenIdle = a => b => a.thenIdle(b)
export const thenSucceed = a => a.thenSucceed()
export const thenWait = a => b => a.thenWait(b)
export const thenWaitAfter = a => b => c => a.thenWaitAfter(b,c)
export const batch = a => b => a.batch(b)
export const maxAttempts = a => b => a.maxAttempts(b)
export const maxTicks = a => b => a.maxTicks(b)
export const padding = a => b => a.padding(b)
export const required = a => b => a.required(b)
export const requiredSuccessfulAttempts = a => b => a.requiredSuccessfulAttempts(b)
export const rotateTest = a => b => a.rotateTest(b)
export const setupTicks = a => b => a.setupTicks(b)
export const structureName = a => b => a.structureName(b)
export const tag = a => b => a.tag(b)
export const addCursorsWithOffset = a => b => c => a.addCursorsWithOffset(b,c)
export const getCursorPosition = a => b => a.getCursorPosition(b)
export const getNumberOfCursors = a => a.getNumberOfCursors()
export const getTotalCharge = a => a.getTotalCharge()
export const attack = a => a.attack()
export const attackEntity = a => b => a.attackEntity(b)
export const breakBlock = a => b => c => a.breakBlock(b,c)
export const disconnect = a => a.disconnect()
export const dropSelectedItem = a => a.dropSelectedItem()
export const fly = a => a.fly()
export const giveItem = a => b => c => a.giveItem(b,c)
export const glide = a => a.glide()
export const interact = a => a.interact()
export const interactWithBlock = a => b => c => a.interactWithBlock(b,c)
export const interactWithEntity = a => b => a.interactWithEntity(b)
export const jump = a => a.jump()
export const lookAtBlock = a => b => a.lookAtBlock(b)
export const lookAtEntity = a => b => a.lookAtEntity(b)
export const lookAtLocation = a => b => a.lookAtLocation(b)
export const move = a => b => c => d => a.move(b,c,d)
export const moveRelative = a => b => c => d => a.moveRelative(b,c,d)
export const moveToBlock = a => b => c => a.moveToBlock(b,c)
export const moveToLocation = a => b => c => a.moveToLocation(b,c)
export const navigateToBlock = a => b => c => a.navigateToBlock(b,c)
export const navigateToEntity = a => b => c => a.navigateToEntity(b,c)
export const navigateToLocation = a => b => c => a.navigateToLocation(b,c)
export const navigateToLocations = a => b => c => a.navigateToLocations(b,c)
export const respawn = a => a.respawn()
export const rotateBody = a => b => a.rotateBody(b)
export const setBodyRotation = a => b => a.setBodyRotation(b)
export const setGameMode = a => b => a.setGameMode(b)
export const setItem = a => b => c => d => a.setItem(b,c,d)
export const stopBreakingBlock = a => a.stopBreakingBlock()
export const stopFlying = a => a.stopFlying()
export const stopGliding = a => a.stopGliding()
export const stopInteracting = a => a.stopInteracting()
export const stopMoving = a => a.stopMoving()
export const stopSwimming = a => a.stopSwimming()
export const stopUsingItem = a => a.stopUsingItem()
export const swim = a => a.swim()
export const useItem = a => b => a.useItem(b)
export const useItemInSlot = a => b => a.useItemInSlot(b)
export const _prim_useItemInSlotOnBlock = a => b => c => d => e => a.useItemInSlotOnBlock(b,c,d,e)
export const _prim_useItemOnBlock = a => b => c => d => e => a.useItemOnBlock(b,c,d,e)
export const assert = a => b => c => a.assert(b,c)
export const assertBlockPresent = a => b => c => d => a.assertBlockPresent(b,c,d)
export const assertBlockState = a => b => c => a.assertBlockState(b,c)
export const assertCanReachLocation = a => b => c => d => a.assertCanReachLocation(b,c,d)
export const assertContainerContains = a => b => c => a.assertContainerContains(b,c)
export const assertContainerEmpty = a => b => a.assertContainerEmpty(b)
export const assertEntityHasArmor = a => b => c => d => e => f => g => a.assertEntityHasArmor(b,c,d,e,f,g)
export const assertEntityHasComponent = a => b => c => d => e => a.assertEntityHasComponent(b,c,d,e)
export const assertEntityInstancePresent = a => b => c => d => a.assertEntityInstancePresent(b,c,d)
export const assertEntityInstancePresentInArea = a => b => c => a.assertEntityInstancePresentInArea(b,c)
export const assertEntityPresent = a => b => c => d => e => a.assertEntityPresent(b,c,d,e)
export const assertEntityPresentInArea = a => b => c => a.assertEntityPresentInArea(b,c)
export const assertEntityState = a => b => c => d => a.assertEntityState(b,c,d)
export const assertEntityTouching = a => b => c => d => a.assertEntityTouching(b,c,d)
export const assertIsWaterlogged = a => b => c => a.assertIsWaterlogged(b,c)
export const assertItemEntityCountIs = a => b => c => d => e => a.assertItemEntityCountIs(b,c,d,e)
export const assertItemEntityPresent = a => b => c => d => e => a.assertItemEntityPresent(b,c,d,e)
export const assertRedstonePower = a => b => c => a.assertRedstonePower(b,c)
export const destroyBlock = a => b => c => a.destroyBlock(b,c)
export const fail = a => b => a.fail(b)
export const failIf = a => b => a.failIf(b)
export const getBlock = a => b => a.getBlock(b)
export const getDimension = a => a.getDimension()
export const getFenceConnectivity = a => b => a.getFenceConnectivity(b)
export const getSculkSpreader = a => b => a.getSculkSpreader(b)
export const getTestDirection = a => a.getTestDirection()
export const idle = a => b => a.idle(b)
export const killAllEntities = a => a.killAllEntities()
export const onPlayerJump = a => b => c => a.onPlayerJump(b,c)
export const pressButton = a => b => a.pressButton(b)
export const print = a => b => a.print(b)
export const pullLever = a => b => a.pullLever(b)
export const pulseRedstone = a => b => c => a.pulseRedstone(b,c)
export const relativeBlockLocation = a => b => a.relativeBlockLocation(b)
export const relativeLocation = a => b => a.relativeLocation(b)
export const removeSimulatedPlayer = a => b => a.removeSimulatedPlayer(b)
export const rotateDirection = a => b => a.rotateDirection(b)
export const rotateVector = a => b => a.rotateVector(b)
export const runAfterDelay = a => b => c => a.runAfterDelay(b,c)
export const runAtTickTime = a => b => c => a.runAtTickTime(b,c)
export const setBlockPermutation = a => b => c => a.setBlockPermutation(b,c)
export const setBlockType = a => b => c => a.setBlockType(b,c)
export const setFluidContainer = a => b => c => a.setFluidContainer(b,c)
export const setTntFuse = a => b => c => a.setTntFuse(b,c)
export const spawn = a => b => c => a.spawn(b,c)
export const spawnAtLocation = a => b => c => a.spawnAtLocation(b,c)
export const spawnItem = a => b => c => a.spawnItem(b,c)
export const spawnSimulatedPlayer = a => b => c => d => a.spawnSimulatedPlayer(b,c,d)
export const spawnWithoutBehaviors = a => b => c => a.spawnWithoutBehaviors(b,c)
export const spawnWithoutBehaviorsAtLocation = a => b => c => a.spawnWithoutBehaviorsAtLocation(b,c)
export const spreadFromFaceTowardDirection = a => b => c => d => a.spreadFromFaceTowardDirection(b,c,d)
export const startSequence = a => a.startSequence()
export const succeed = a => a.succeed()
export const succeedIf = a => b => a.succeedIf(b)
export const succeedOnTick = a => b => a.succeedOnTick(b)
export const succeedOnTickWhen = a => b => c => a.succeedOnTickWhen(b,c)
export const succeedWhen = a => b => a.succeedWhen(b)
export const succeedWhenBlockPresent = a => b => c => d => a.succeedWhenBlockPresent(b,c,d)
export const succeedWhenEntityHasComponent = a => b => c => d => e => a.succeedWhenEntityHasComponent(b,c,d,e)
export const succeedWhenEntityPresent = a => b => c => d => a.succeedWhenEntityPresent(b,c,d)
export const triggerInternalBlockEvent = a => b => c => d => a.triggerInternalBlockEvent(b,c,d)
export const until = a => b => a.until(b)
export const walkTo = a => b => c => d => a.walkTo(b,c,d)
export const walkToLocation = a => b => c => d => a.walkToLocation(b,c,d)
export const worldBlockLocation = a => b => a.worldBlockLocation(b)
export const worldLocation = a => b => a.worldLocation(b)