import * as M from "@minecraft/server"
export const _prim_canPlace = a => b => c => a.canPlace(b,c)
export const _prim_getComponent_Block = a => b => a.getComponent(b)
export const getItemStack_Block = a => b => c => a.getItemStack(b,c)
export const _prim_getRedstonePower = a => a.getRedstonePower()
export const getTags_Block = a => a.getTags()
export const hasTag_Block = a => b => a.hasTag(b)
export const isValid_Block = a => a.isValid()
export const setPermutation = a => b => a.setPermutation(b)
export const setType = a => b => a.setType(b)
export const trySetPermutation = a => b => a.trySetPermutation(b)
export const mk_BlockAreaSize = a => b => c => new M.BlockAreaSize(a,b,c)
export const equals_BlockAreaSize = a => b => a.equals(b)
export const subscribe_BlockBreakAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_BlockBreakAfterEventSignal = a => b => a.unsubscribe(b)
export const isValid_BlockComponent = a => a.isValid()
export const subscribe_BlockExplodeAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_BlockExplodeAfterEventSignal = a => b => a.unsubscribe(b)
export const isValid_BlockInventoryComponent = a => a.isValid()
export const isValidLiquid_BlockLavaContainerComponent = a => a.isValidLiquid()
export const isValidLiquid_BlockLiquidContainerComponent = a => a.isValidLiquid()
export const isValid_BlockLiquidContainerComponent = a => a.isValid()
export const clone_BlockPermutation = a => a.clone()
export const getAllStates = a => a.getAllStates()
export const getItemStack_BlockPermutation = a => b => a.getItemStack(b)
export const _prim_getState = a => b => a.getState(b)
export const getTags_BlockPermutation = a => a.getTags()
export const hasTag_BlockPermutation = a => b => a.hasTag(b)
export const _prim_matches = a => b => c => a.matches(b,c)
export const _prim_resolve = a => b => M.BlockPermutation.resolve(a,b)
export const withState = a => b => c => a.withState(b,c)
export const getAttachedBlocks = a => a.getAttachedBlocks()
export const isValid_BlockPistonComponent = a => a.isValid()
export const subscribe_BlockPlaceAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_BlockPlaceAfterEventSignal = a => b => a.unsubscribe(b)
export const setPotionType = a => b => a.setPotionType(b)
export const isValidLiquid_BlockPotionContainerComponent = a => a.isValidLiquid()
export const isValid_BlockPotionContainerComponent = a => a.isValid()
export const clearRecord = a => a.clearRecord()
export const isPlaying = a => a.isPlaying()
export const setRecord = a => b => a.setRecord(b)
export const isValid_BlockRecordPlayerComponent = a => a.isValid()
export const _prim_getRawText = a => b => a.getRawText(b)
export const _prim_getText = a => b => a.getText(b)
export const _prim_getTextDyeColor = a => b => a.getTextDyeColor(b)
export const _prim_setText = a => b => c => a.setText(b,c)
export const _prim_setTextDyeColor = a => b => c => a.setTextDyeColor(b,c)
export const setWaxed = a => a.setWaxed()
export const isValid_BlockSignComponent = a => a.isValid()
export const isValidLiquid_BlockSnowContainerComponent = a => a.isValidLiquid()
export const isValid_BlockSnowContainerComponent = a => a.isValid()
export const get_BlockStates = a => M.BlockStates.get(a)
export const getAll_BlockStates = () => M.BlockStates.getAll()
export const _prim_get_BlockTypes = a => M.BlockTypes.get(a)
export const getAll_BlockTypes = () => M.BlockTypes.getAll()
export const doesLocationTouchFaces = a => b => M.BlockVolumeUtils.doesLocationTouchFaces(a,b)
export const doesVolumeTouchFaces = a => b => M.BlockVolumeUtils.doesVolumeTouchFaces(a,b)
export const equals_BlockVolumeUtils = a => b => M.BlockVolumeUtils.equals(a,b)
export const getBlockLocationIterator_BlockVolumeUtils = a => M.BlockVolumeUtils.getBlockLocationIterator(a)
export const getBoundingBox_BlockVolumeUtils = a => M.BlockVolumeUtils.getBoundingBox(a)
export const getCapacity = a => M.BlockVolumeUtils.getCapacity(a)
export const getMax_BlockVolumeUtils = a => M.BlockVolumeUtils.getMax(a)
export const getMin_BlockVolumeUtils = a => M.BlockVolumeUtils.getMin(a)
export const getSpan_BlockVolumeUtils = a => M.BlockVolumeUtils.getSpan(a)
export const intersects_BlockVolumeUtils = a => b => M.BlockVolumeUtils.intersects(a,b)
export const isInside_BlockVolumeUtils = a => b => M.BlockVolumeUtils.isInside(a,b)
export const translate_BlockVolumeUtils = a => b => M.BlockVolumeUtils.translate(a,b)
export const addDye = a => b => a.addDye(b)
export const getCustomColor = a => a.getCustomColor()
export const setCustomColor = a => b => a.setCustomColor(b)
export const isValidLiquid_BlockWaterContainerComponent = a => a.isValidLiquid()
export const isValid_BlockWaterContainerComponent = a => a.isValid()
export const createValid = a => b => M.BoundingBoxUtils.createValid(a,b)
export const dilate = a => b => M.BoundingBoxUtils.dilate(a,b)
export const equals_BoundingBoxUtils = a => b => M.BoundingBoxUtils.equals(a,b)
export const expand = a => b => M.BoundingBoxUtils.expand(a,b)
export const getCenter = a => M.BoundingBoxUtils.getCenter(a)
export const _prim_getIntersection = a => b => M.BoundingBoxUtils.getIntersection(a,b)
export const getSpan_BoundingBoxUtils = a => M.BoundingBoxUtils.getSpan(a)
export const intersects_BoundingBoxUtils = a => b => M.BoundingBoxUtils.intersects(a,b)
export const isInside_BoundingBoxUtils = a => b => M.BoundingBoxUtils.isInside(a,b)
export const isValid_BoundingBoxUtils = a => M.BoundingBoxUtils.isValid(a)
export const translate_BoundingBoxUtils = a => b => M.BoundingBoxUtils.translate(a,b)
export const subscribe_ButtonPushAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ButtonPushAfterEventSignal = a => b => a.unsubscribe(b)
export const clear_Camera = a => a.clear()
export const _prim_fade = a => b => a.fade(b)
export const _prim_setCamera = a => b => c => a.setCamera(b,c)
export const getTargets_ChatSendAfterEvent = a => a.getTargets()
export const subscribe_ChatSendAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ChatSendAfterEventSignal = a => b => a.unsubscribe(b)
export const setTargets = a => b => a.setTargets(b)
export const getTargets_ChatSendBeforeEvent = a => a.getTargets()
export const subscribe_ChatSendBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ChatSendBeforeEventSignal = a => b => a.unsubscribe(b)
export const isValid_Component = a => a.isValid()
export const clear_CompoundBlockVolume = a => a.clear()
export const _prim_mk_CompoundBlockVolume = a => new M.CompoundBlockVolume(a)
export const getBlockLocationIterator_CompoundBlockVolume = a => a.getBlockLocationIterator()
export const getBoundingBox_CompoundBlockVolume = a => a.getBoundingBox()
export const getMax_CompoundBlockVolume = a => a.getMax()
export const getMin_CompoundBlockVolume = a => a.getMin()
export const getOrigin = a => a.getOrigin()
export const isEmpty = a => a.isEmpty()
export const isInside_CompoundBlockVolume = a => b => a.isInside(b)
export const _prim_peekLastVolume = a => b => a.peekLastVolume(b)
export const popVolume = a => a.popVolume()
export const pushVolume = a => b => a.pushVolume(b)
export const replaceOrAddLastVolume = a => b => a.replaceOrAddLastVolume(b)
export const _prim_setOrigin = a => b => c => a.setOrigin(b,c)
export const _prim_translateOrigin = a => b => c => a.translateOrigin(b,c)
export const addItem = a => b => a.addItem(b)
export const clearAll = a => a.clearAll()
export const _prim_getItem_Container = a => b => a.getItem(b)
export const getSlot = a => b => a.getSlot(b)
export const isValid_Container = a => a.isValid()
export const moveItem = a => b => c => d => a.moveItem(b,c,d)
export const _prim_setItem_Container = a => b => c => a.setItem(b,c)
export const swapItems = a => b => c => d => a.swapItems(b,c,d)
export const transferItem = a => b => c => a.transferItem(b,c)
export const _prim_getItem_ContainerSlot = a => a.getItem()
export const getLore_ContainerSlot = a => a.getLore()
export const getTags_ContainerSlot = a => a.getTags()
export const hasTag_ContainerSlot = a => b => a.hasTag(b)
export const isStackableWith_ContainerSlot = a => b => a.isStackableWith(b)
export const isValid_ContainerSlot = a => a.isValid()
export const _prim_setCanDestroy_ContainerSlot = a => b => a.setCanDestroy(b)
export const _prim_setCanPlaceOn_ContainerSlot = a => b => a.setCanPlaceOn(b)
export const _prim_setItem_ContainerSlot = a => b => a.setItem(b)
export const _prim_setLore_ContainerSlot = a => b => a.setLore(b)
export const getModifiers_DataDrivenEntityTriggerAfterEvent = a => a.getModifiers()
export const _prim_subscribe_DataDrivenEntityTriggerAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_DataDrivenEntityTriggerAfterEventSignal = a => b => a.unsubscribe(b)
export const getModifiers_DataDrivenEntityTriggerBeforeEvent = a => a.getModifiers()
export const setModifiers = a => b => a.setModifiers(b)
export const _prim_subscribe_DataDrivenEntityTriggerBeforeEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_DataDrivenEntityTriggerBeforeEventSignal = a => b => a.unsubscribe(b)
export const mk_DefinitionModifier = () => new M.DefinitionModifier()
export const getComponentGroupsToAdd = a => a.getComponentGroupsToAdd()
export const getComponentGroupsToRemove = a => a.getComponentGroupsToRemove()
export const getTriggers = a => a.getTriggers()
export const setComponentGroupsToAdd = a => b => a.setComponentGroupsToAdd(b)
export const setComponentGroupsToRemove = a => b => a.setComponentGroupsToRemove(b)
export const setTriggers = a => b => a.setTriggers(b)
export const _prim_createExplosion = a => b => c => d => a.createExplosion(b,c,d)
export const _prim_fillBlocks = a => b => c => d => e => a.fillBlocks(b,c,d,e)
export const _prim_getBlock = a => b => a.getBlock(b)
export const _prim_getBlockFromRay = a => b => c => d => a.getBlockFromRay(b,c,d)
export const _prim_getEntities = a => b => a.getEntities(b)
export const getEntitiesAtBlockLocation = a => b => a.getEntitiesAtBlockLocation(b)
export const _prim_getEntitiesFromRay = a => b => c => d => a.getEntitiesFromRay(b,c,d)
export const _prim_getPlayers_Dimension = a => b => a.getPlayers(b)
export const runCommand_Dimension = a => b => a.runCommand(b)
export const runCommandAsync_Dimension = a => b => a.runCommandAsync(b)
export const _prim_setWeather = a => b => a.setWeather(b)
export const spawnEntity = a => b => c => a.spawnEntity(b,c)
export const spawnItem = a => b => c => a.spawnItem(b,c)
export const _prim_spawnParticle = a => b => c => d => a.spawnParticle(b,c,d)
export const _prim_get_DimensionTypes = a => M.DimensionTypes.get(a)
export const getAll_DimensionTypes = () => M.DimensionTypes.getAll()
export const mk_DynamicPropertiesDefinition = () => new M.DynamicPropertiesDefinition()
export const _prim_defineBoolean = a => b => c => a.defineBoolean(b,c)
export const _prim_defineNumber = a => b => c => a.defineNumber(b,c)
export const _prim_defineString = a => b => c => d => a.defineString(b,c,d)
export const _prim_defineVector = a => b => c => a.defineVector(b,c)
export const isValid_Effect = a => a.isValid()
export const _prim_subscribe_EffectAddAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EffectAddAfterEventSignal = a => b => a.unsubscribe(b)
export const getName = a => a.getName()
export const _prim_get_EffectTypes = a => M.EffectTypes.get(a)
export const getAll_EffectTypes = () => M.EffectTypes.getAll()
export const mk_Enchantment = a => b => new M.Enchantment(a,b)
export const addEnchantment = a => b => a.addEnchantment(b)
export const canAddEnchantment = a => b => a.canAddEnchantment(b)
export const mk_EnchantmentList = a => new M.EnchantmentList(a)
export const _prim_getEnchantment = a => b => a.getEnchantment(b)
export const hasEnchantment = a => b => a.hasEnchantment(b)
export const removeEnchantment = a => b => a.removeEnchantment(b)
export const _prim_get_EnchantmentTypes = a => M.EnchantmentTypes.get(a)
export const _prim_addEffect_Entity = a => b => c => d => a.addEffect(b,c,d)
export const addTag_Entity = a => b => a.addTag(b)
export const _prim_applyDamage_Entity = a => b => c => a.applyDamage(b,c)
export const applyImpulse_Entity = a => b => a.applyImpulse(b)
export const applyKnockback_Entity = a => b => c => d => e => a.applyKnockback(b,c,d,e)
export const clearVelocity_Entity = a => a.clearVelocity()
export const _prim_extinguishFire_Entity = a => b => a.extinguishFire(b)
export const _prim_getBlockFromViewDirection_Entity = a => b => a.getBlockFromViewDirection(b)
export const _prim_getComponent_Entity = a => b => a.getComponent(b)
export const getComponents_Entity = a => a.getComponents()
export const _prim_getDynamicProperty_Entity = a => b => a.getDynamicProperty(b)
export const _prim_getEffect_Entity = a => b => a.getEffect(b)
export const getEffects_Entity = a => a.getEffects()
export const _prim_getEntitiesFromViewDirection_Entity = a => b => a.getEntitiesFromViewDirection(b)
export const getHeadLocation_Entity = a => a.getHeadLocation()
export const getRotation_Entity = a => a.getRotation()
export const getTags_Entity = a => a.getTags()
export const getVelocity_Entity = a => a.getVelocity()
export const getViewDirection_Entity = a => a.getViewDirection()
export const hasComponent_Entity = a => b => a.hasComponent(b)
export const hasTag_Entity = a => b => a.hasTag(b)
export const isValid_Entity = a => a.isValid()
export const kill_Entity = a => a.kill()
export const _prim_playAnimation_Entity = a => b => c => a.playAnimation(b,c)
export const remove_Entity = a => a.remove()
export const removeDynamicProperty_Entity = a => b => a.removeDynamicProperty(b)
export const removeEffect_Entity = a => b => a.removeEffect(b)
export const removeTag_Entity = a => b => a.removeTag(b)
export const runCommand_Entity = a => b => a.runCommand(b)
export const runCommandAsync_Entity = a => b => a.runCommandAsync(b)
export const setDynamicProperty_Entity = a => b => c => a.setDynamicProperty(b,c)
export const _prim_setOnFire_Entity = a => b => c => a.setOnFire(b,c)
export const setRotation_Entity = a => b => a.setRotation(b)
export const _prim_teleport_Entity = a => b => c => a.teleport(b,c)
export const triggerEvent_Entity = a => b => a.triggerEvent(b)
export const _prim_tryTeleport_Entity = a => b => c => a.tryTeleport(b,c)
export const getDropItems = a => a.getDropItems()
export const getFeedItems_EntityAgeableComponent = a => a.getFeedItems()
export const resetToDefaultValue_EntityAttributeComponent = a => a.resetToDefaultValue()
export const resetToMaxValue_EntityAttributeComponent = a => a.resetToMaxValue()
export const resetToMinValue_EntityAttributeComponent = a => a.resetToMinValue()
export const setCurrentValue_EntityAttributeComponent = a => b => a.setCurrentValue(b)
export const getBreatheBlocks = a => a.getBreatheBlocks()
export const getNonBreatheBlocks = a => a.getNonBreatheBlocks()
export const setAirSupply = a => b => a.setAirSupply(b)
export const isValid_EntityComponent = a => a.isValid()
export const _prim_subscribe_EntityDieAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityDieAfterEventSignal = a => b => a.unsubscribe(b)
export const _prim_getEquipment = a => b => a.getEquipment(b)
export const _prim_getEquipmentSlot = a => b => a.getEquipmentSlot(b)
export const _prim_setEquipment = a => b => c => a.setEquipment(b,c)
export const isValid_EntityEquippableComponent = a => a.isValid()
export const isValid_EntityFireImmuneComponent = a => a.isValid()
export const isValid_EntityFloatsInLiquidComponent = a => a.isValid()
export const isValid_EntityFlyingSpeedComponent = a => a.isValid()
export const isValid_EntityFrictionModifierComponent = a => a.isValid()
export const isValid_EntityGroundOffsetComponent = a => a.isValid()
export const getFeedItems_EntityHealableComponent = a => a.getFeedItems()
export const isValid_EntityHealableComponent = a => a.isValid()
export const _prim_subscribe_EntityHealthChangedAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityHealthChangedAfterEventSignal = a => b => a.unsubscribe(b)
export const resetToDefaultValue_EntityHealthComponent = a => a.resetToDefaultValue()
export const resetToMaxValue_EntityHealthComponent = a => a.resetToMaxValue()
export const resetToMinValue_EntityHealthComponent = a => a.resetToMinValue()
export const setCurrentValue_EntityHealthComponent = a => b => a.setCurrentValue(b)
export const _prim_subscribe_EntityHitBlockAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityHitBlockAfterEventSignal = a => b => a.unsubscribe(b)
export const _prim_subscribe_EntityHitEntityAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityHitEntityAfterEventSignal = a => b => a.unsubscribe(b)
export const _prim_subscribe_EntityHurtAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityHurtAfterEventSignal = a => b => a.unsubscribe(b)
export const isValid_EntityInventoryComponent = a => a.isValid()
export const isValid_EntityIsBabyComponent = a => a.isValid()
export const isValid_EntityIsChargedComponent = a => a.isValid()
export const isValid_EntityIsChestedComponent = a => a.isValid()
export const isValid_EntityIsDyeableComponent = a => a.isValid()
export const isValid_EntityIsHiddenWhenInvisibleComponent = a => a.isValid()
export const isValid_EntityIsIgnitedComponent = a => a.isValid()
export const isValid_EntityIsIllagerCaptainComponent = a => a.isValid()
export const isValid_EntityIsSaddledComponent = a => a.isValid()
export const isValid_EntityIsShakingComponent = a => a.isValid()
export const isValid_EntityIsShearedComponent = a => a.isValid()
export const isValid_EntityIsStackableComponent = a => a.isValid()
export const isValid_EntityIsStunnedComponent = a => a.isValid()
export const isValid_EntityIsTamedComponent = a => a.isValid()
export const isValid_EntityItemComponent = a => a.isValid()
export const resetToDefaultValue_EntityLavaMovementComponent = a => a.resetToDefaultValue()
export const resetToMaxValue_EntityLavaMovementComponent = a => a.resetToMaxValue()
export const resetToMinValue_EntityLavaMovementComponent = a => a.resetToMinValue()
export const setCurrentValue_EntityLavaMovementComponent = a => b => a.setCurrentValue(b)
export const leash = a => b => a.leash(b)
export const unleash = a => a.unleash()
export const isValid_EntityLeashableComponent = a => a.isValid()
export const isValid_EntityMarkVariantComponent = a => a.isValid()
export const setTamed = a => b => a.setTamed(b)
export const isValid_EntityMountTamingComponent = a => a.isValid()
export const resetToDefaultValue_EntityMovementComponent = a => a.resetToDefaultValue()
export const resetToMaxValue_EntityMovementComponent = a => a.resetToMaxValue()
export const resetToMinValue_EntityMovementComponent = a => a.resetToMinValue()
export const setCurrentValue_EntityMovementComponent = a => b => a.setCurrentValue(b)
export const isValid_EntityNavigationComponent = a => a.isValid()
export const isValid_EntityNavigationFloatComponent = a => a.isValid()
export const isValid_EntityNavigationFlyComponent = a => a.isValid()
export const isValid_EntityNavigationGenericComponent = a => a.isValid()
export const isValid_EntityNavigationHoverComponent = a => a.isValid()
export const isValid_EntityNavigationWalkComponent = a => a.isValid()
export const isValid_EntityOnFireComponent = a => a.isValid()
export const isValid_EntityPushThroughComponent = a => a.isValid()
export const _prim_subscribe_EntityRemovedAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_EntityRemovedAfterEventSignal = a => b => a.unsubscribe(b)
export const addRider = a => b => a.addRider(b)
export const ejectRider = a => b => a.ejectRider(b)
export const ejectRiders = a => a.ejectRiders()
export const getFamilyTypes = a => a.getFamilyTypes()
export const getRiders = a => a.getRiders()
export const getSeats = a => a.getSeats()
export const isValid_EntityRideableComponent = a => a.isValid()
export const isValid_EntityRidingComponent = a => a.isValid()
export const isValid_EntityScaleComponent = a => a.isValid()
export const isValid_EntitySkinIdComponent = a => a.isValid()
export const subscribe_EntitySpawnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_EntitySpawnAfterEventSignal = a => b => a.unsubscribe(b)
export const isValid_EntityStrengthComponent = a => a.isValid()
export const getTameItems = a => a.getTameItems()
export const tame = a => a.tame()
export const isValid_EntityTameableComponent = a => a.isValid()
export const get_EntityTypes = a => M.EntityTypes.get(a)
export const getAll_EntityTypes = () => M.EntityTypes.getAll()
export const resetToDefaultValue_EntityUnderwaterMovementComponent = a => a.resetToDefaultValue()
export const resetToMaxValue_EntityUnderwaterMovementComponent = a => a.resetToMaxValue()
export const resetToMinValue_EntityUnderwaterMovementComponent = a => a.resetToMinValue()
export const setCurrentValue_EntityUnderwaterMovementComponent = a => b => a.setCurrentValue(b)
export const isValid_EntityVariantComponent = a => a.isValid()
export const isValid_EntityWantsJockeyComponent = a => a.isValid()
export const getImpactedBlocks_ExplosionAfterEvent = a => a.getImpactedBlocks()
export const subscribe_ExplosionAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ExplosionAfterEventSignal = a => b => a.unsubscribe(b)
export const setImpactedBlocks = a => b => a.setImpactedBlocks(b)
export const getImpactedBlocks_ExplosionBeforeEvent = a => a.getImpactedBlocks()
export const subscribe_ExplosionBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ExplosionBeforeEventSignal = a => b => a.unsubscribe(b)
export const getEffects_FeedItem = a => a.getEffects()
export const subscribe_IButtonPushAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_IButtonPushAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ILeverActionAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ILeverActionAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_IPlayerJoinAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_IPlayerJoinAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_IPlayerLeaveAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_IPlayerLeaveAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_IPlayerSpawnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_IPlayerSpawnAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemCompleteUseAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemCompleteUseAfterEventSignal = a => b => a.unsubscribe(b)
export const isValid_ItemComponent = a => a.isValid()
export const startCooldown = a => b => a.startCooldown(b)
export const isValid_ItemCooldownComponent = a => a.isValid()
export const subscribe_ItemDefinitionAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemDefinitionAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemDefinitionBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemDefinitionBeforeEventSignal = a => b => a.unsubscribe(b)
export const getDamageChance = a => b => a.getDamageChance(b)
export const getDamageRange = a => a.getDamageRange()
export const isValid_ItemDurabilityComponent = a => a.isValid()
export const removeAllEnchantments = a => a.removeAllEnchantments()
export const isValid_ItemEnchantsComponent = a => a.isValid()
export const isValid_ItemFoodComponent = a => a.isValid()
export const subscribe_ItemReleaseUseAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemReleaseUseAfterEventSignal = a => b => a.unsubscribe(b)
export const clone_ItemStack = a => a.clone()
export const mk_ItemStack = a => b => new M.ItemStack(a,b)
export const _prim_getComponent_ItemStack = a => b => a.getComponent(b)
export const getComponents_ItemStack = a => a.getComponents()
export const getLore_ItemStack = a => a.getLore()
export const getTags_ItemStack = a => a.getTags()
export const hasComponent_ItemStack = a => b => a.hasComponent(b)
export const hasTag_ItemStack = a => b => a.hasTag(b)
export const isStackableWith_ItemStack = a => b => a.isStackableWith(b)
export const _prim_setCanDestroy_ItemStack = a => b => a.setCanDestroy(b)
export const _prim_setCanPlaceOn_ItemStack = a => b => a.setCanPlaceOn(b)
export const _prim_setLore_ItemStack = a => b => a.setLore(b)
export const triggerEvent_ItemStack = a => b => a.triggerEvent(b)
export const subscribe_ItemStartUseAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemStartUseAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemStartUseOnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemStartUseOnAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemStopUseAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemStopUseAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemStopUseOnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemStopUseOnAfterEventSignal = a => b => a.unsubscribe(b)
export const get_ItemTypes = a => M.ItemTypes.get(a)
export const getAll_ItemTypes = () => M.ItemTypes.getAll()
export const subscribe_ItemUseAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemUseAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemUseBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemUseBeforeEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemUseOnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemUseOnAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ItemUseOnBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ItemUseOnBeforeEventSignal = a => b => a.unsubscribe(b)
export const subscribe_LeverActionAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_LeverActionAfterEventSignal = a => b => a.unsubscribe(b)
export const mk_MolangVariableMap = () => new M.MolangVariableMap()
export const setColorRGB = a => b => c => a.setColorRGB(b,c)
export const setColorRGBA = a => b => c => a.setColorRGBA(b,c)
export const setFloat = a => b => c => a.setFloat(b,c)
export const setSpeedAndDirection = a => b => c => d => a.setSpeedAndDirection(b,c,d)
export const setVector3 = a => b => c => a.setVector3(b,c)
export const getPath = a => a.getPath()
export const subscribe_PistonActivateAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PistonActivateAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_PistonActivateBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PistonActivateBeforeEventSignal = a => b => a.unsubscribe(b)
export const addExperience = a => b => a.addExperience(b)
export const addLevels = a => b => a.addLevels(b)
export const getItemCooldown = a => b => a.getItemCooldown(b)
export const _prim_getSpawnPoint = a => a.getSpawnPoint()
export const getTotalXp = a => a.getTotalXp()
export const isOp = a => a.isOp()
export const _prim_playSound_Player = a => b => c => a.playSound(b,c)
export const postClientMessage = a => b => c => a.postClientMessage(b,c)
export const resetLevel = a => a.resetLevel()
export const sendMessage_Player = a => b => a.sendMessage(b)
export const setOp = a => b => a.setOp(b)
export const _prim_setSpawnPoint = a => b => a.setSpawnPoint(b)
export const startItemCooldown = a => b => c => a.startItemCooldown(b,c)
export const _prim_addEffect_Player = a => b => c => d => a.addEffect(b,c,d)
export const addTag_Player = a => b => a.addTag(b)
export const _prim_applyDamage_Player = a => b => c => a.applyDamage(b,c)
export const applyImpulse_Player = a => b => a.applyImpulse(b)
export const applyKnockback_Player = a => b => c => d => e => a.applyKnockback(b,c,d,e)
export const clearVelocity_Player = a => a.clearVelocity()
export const _prim_extinguishFire_Player = a => b => a.extinguishFire(b)
export const _prim_getBlockFromViewDirection_Player = a => b => a.getBlockFromViewDirection(b)
export const _prim_getComponent_Player = a => b => a.getComponent(b)
export const getComponents_Player = a => a.getComponents()
export const _prim_getDynamicProperty_Player = a => b => a.getDynamicProperty(b)
export const _prim_getEffect_Player = a => b => a.getEffect(b)
export const getEffects_Player = a => a.getEffects()
export const _prim_getEntitiesFromViewDirection_Player = a => b => a.getEntitiesFromViewDirection(b)
export const getHeadLocation_Player = a => a.getHeadLocation()
export const getRotation_Player = a => a.getRotation()
export const getTags_Player = a => a.getTags()
export const getVelocity_Player = a => a.getVelocity()
export const getViewDirection_Player = a => a.getViewDirection()
export const hasComponent_Player = a => b => a.hasComponent(b)
export const hasTag_Player = a => b => a.hasTag(b)
export const isValid_Player = a => a.isValid()
export const kill_Player = a => a.kill()
export const _prim_playAnimation_Player = a => b => c => a.playAnimation(b,c)
export const remove_Player = a => a.remove()
export const removeDynamicProperty_Player = a => b => a.removeDynamicProperty(b)
export const removeEffect_Player = a => b => a.removeEffect(b)
export const removeTag_Player = a => b => a.removeTag(b)
export const runCommand_Player = a => b => a.runCommand(b)
export const runCommandAsync_Player = a => b => a.runCommandAsync(b)
export const setDynamicProperty_Player = a => b => c => a.setDynamicProperty(b,c)
export const _prim_setOnFire_Player = a => b => c => a.setOnFire(b,c)
export const setRotation_Player = a => b => a.setRotation(b)
export const _prim_teleport_Player = a => b => c => a.teleport(b,c)
export const triggerEvent_Player = a => b => a.triggerEvent(b)
export const _prim_tryTeleport_Player = a => b => c => a.tryTeleport(b,c)
export const subscribe_PlayerJoinAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PlayerJoinAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_PlayerLeaveAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PlayerLeaveAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_PlayerSpawnAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PlayerSpawnAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_PressurePlatePopAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PressurePlatePopAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_PressurePlatePushAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_PressurePlatePushAfterEventSignal = a => b => a.unsubscribe(b)
export const getBlockHit = a => a.getBlockHit()
export const subscribe_ProjectileHitBlockAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ProjectileHitBlockAfterEventSignal = a => b => a.unsubscribe(b)
export const getEntityHit = a => a.getEntityHit()
export const subscribe_ProjectileHitEntityAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ProjectileHitEntityAfterEventSignal = a => b => a.unsubscribe(b)
export const registerEntityTypeDynamicProperties = a => b => c => a.registerEntityTypeDynamicProperties(b,c)
export const registerWorldDynamicProperties = a => b => a.registerWorldDynamicProperties(b)
export const addObjective = a => b => c => a.addObjective(b,c)
export const _prim_clearObjectiveAtDisplaySlot = a => b => a.clearObjectiveAtDisplaySlot(b)
export const _prim_getObjective = a => b => a.getObjective(b)
export const _prim_getObjectiveAtDisplaySlot = a => b => a.getObjectiveAtDisplaySlot(b)
export const getObjectives = a => a.getObjectives()
export const getParticipants_Scoreboard = a => a.getParticipants()
export const removeObjective = a => b => a.removeObjective(b)
export const _prim_setObjectiveAtDisplaySlot = a => b => c => a.setObjectiveAtDisplaySlot(b,c)
export const getEntity_ScoreboardIdentity = a => a.getEntity()
export const isValid_ScoreboardIdentity = a => a.isValid()
export const addScore = a => b => c => a.addScore(b,c)
export const getParticipants_ScoreboardObjective = a => a.getParticipants()
export const _prim_getScore = a => b => a.getScore(b)
export const getScores = a => a.getScores()
export const hasParticipant = a => b => a.hasParticipant(b)
export const isValid_ScoreboardObjective = a => a.isValid()
export const removeParticipant = a => b => a.removeParticipant(b)
export const setScore = a => b => c => a.setScore(b,c)
export const isValid_ScreenDisplay = a => a.isValid()
export const setActionBar = a => b => a.setActionBar(b)
export const _prim_setTitle = a => b => c => a.setTitle(b,c)
export const updateSubtitle = a => b => a.updateSubtitle(b)
export const _prim_subscribe_ScriptEventCommandMessageAfterEventSignal = a => b => c => a.subscribe(b,c)
export const unsubscribe_ScriptEventCommandMessageAfterEventSignal = a => b => a.unsubscribe(b)
export const subscribe_ServerMessageAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_ServerMessageAfterEventSignal = a => b => a.unsubscribe(b)
export const clearRun = a => b => a.clearRun(b)
export const run = a => b => a.run(b)
export const _prim_runInterval = a => b => c => a.runInterval(b,c)
export const _prim_runTimeout = a => b => c => a.runTimeout(b,c)
export const subscribe_TargetBlockHitAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_TargetBlockHitAfterEventSignal = a => b => a.unsubscribe(b)
export const mk_Trigger = a => new M.Trigger(a)
export const subscribe_TripWireTripAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_TripWireTripAfterEventSignal = a => b => a.unsubscribe(b)
export const add = a => b => M.Vector.add(a,b)
export const mk_Vector = a => b => c => new M.Vector(a,b,c)
export const cross = a => b => M.Vector.cross(a,b)
export const distance = a => b => M.Vector.distance(a,b)
export const divide = a => b => M.Vector.divide(a,b)
export const equals_Vector = a => b => a.equals(b)
export const length = a => a.length()
export const lengthSquared = a => a.lengthSquared()
export const lerp = a => b => c => M.Vector.lerp(a,b,c)
export const max = a => b => M.Vector.max(a,b)
export const min = a => b => M.Vector.min(a,b)
export const multiply = a => b => M.Vector.multiply(a,b)
export const normalized = a => a.normalized()
export const slerp = a => b => c => M.Vector.slerp(a,b,c)
export const subtract = a => b => M.Vector.subtract(a,b)
export const subscribe_WatchdogTerminateBeforeEventSignal = a => b => a.subscribe(b)
export const unsubscribe_WatchdogTerminateBeforeEventSignal = a => b => a.unsubscribe(b)
export const subscribe_WeatherChangeAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_WeatherChangeAfterEventSignal = a => b => a.unsubscribe(b)
export const broadcastClientMessage = a => b => c => a.broadcastClientMessage(b,c)
export const getAbsoluteTime = a => a.getAbsoluteTime()
export const getAllPlayers = a => a.getAllPlayers()
export const getDay = a => a.getDay()
export const getDefaultSpawnLocation = a => a.getDefaultSpawnLocation()
export const getDimension = a => b => a.getDimension(b)
export const _prim_getDynamicProperty_World = a => b => a.getDynamicProperty(b)
export const _prim_getEntity_World = a => b => a.getEntity(b)
export const getMoonPhase = a => a.getMoonPhase()
export const _prim_getPlayers_World = a => b => a.getPlayers(b)
export const getTimeOfDay = a => a.getTimeOfDay()
export const _prim_playMusic = a => b => c => a.playMusic(b,c)
export const _prim_playSound_World = a => b => c => d => a.playSound(b,c,d)
export const _prim_queueMusic = a => b => c => a.queueMusic(b,c)
export const removeDynamicProperty_World = a => b => a.removeDynamicProperty(b)
export const sendMessage_World = a => b => a.sendMessage(b)
export const setAbsoluteTime = a => b => a.setAbsoluteTime(b)
export const setDefaultSpawnLocation = a => b => a.setDefaultSpawnLocation(b)
export const setDynamicProperty_World = a => b => c => a.setDynamicProperty(b,c)
export const setTimeOfDay = a => b => a.setTimeOfDay(b)
export const stopMusic = a => a.stopMusic()
export const subscribe_WorldInitializeAfterEventSignal = a => b => a.subscribe(b)
export const unsubscribe_WorldInitializeAfterEventSignal = a => b => a.unsubscribe(b)
export const system = M.system
export const world = M.world