import * as M from "@minecraft/server-ui"
export const body_ActionFormData = a => b => a.body(b)
export const _prim_button = a => b => c => a.button(b,c)
export const mk_ActionFormData = () => new M.ActionFormData()
export const show_ActionFormData = a => b => a.show(b)
export const title_ActionFormData = a => b => a.title(b)
export const body_MessageFormData = a => b => a.body(b)
export const button1 = a => b => a.button1(b)
export const button2 = a => b => a.button2(b)
export const mk_MessageFormData = () => new M.MessageFormData()
export const show_MessageFormData = a => b => a.show(b)
export const title_MessageFormData = a => b => a.title(b)
export const mk_ModalFormData = () => new M.ModalFormData()
export const _prim_dropdown = a => b => c => d => a.dropdown(b,c,d)
export const show_ModalFormData = a => b => a.show(b)
export const _prim_slider = a => b => c => d => e => f => a.slider(b,c,d,e,f)
export const _prim_textField = a => b => c => d => a.textField(b,c,d)
export const title_ModalFormData = a => b => a.title(b)
export const _prim_toggle = a => b => c => a.toggle(b,c)